name: pull docker image and push to ali registry

on:
  release:
    types: [created]

jobs:
  build-core-macos-12:
    env:
      GIT_COMMIT: ${{ github.sha }}
      SYNERGY_NO_LEGACY: "1"
      SYNERGY_NO_TESTS: "1"
      SYNERGY_STATIC_OPENSSL: "1"
    runs-on: macos-12

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - name: Install brew dependencies
        run: |
          brew list openssl &>/dev/null || brew install openssl

      - name: Build
        env:
          #CMAKE_OSX_DEPLOYMENT_TARGET: ${{ matrix.target }}
          CMAKE_OSX_ARCHITECTURES=x86_64
        run: |
          mkdir -v build
          cd build
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH="$(brew --prefix openssl)" ..
          pwd
          ls -a
          . ./version
          make -j

      - uses: actions/upload-artifact@v2
        #if: "github.event_name == 'pull_request'"
        with:
          name: macos-12-build-test
          path: build/bin/*
          retention-days: 1
