name: build package for macOS-12

on: workflow_dispatch
jobs:
  build-core-macos-12:
    env:
      GIT_COMMIT: ${{ github.sha }}
      #SYNERGY_NO_LEGACY: "1"
      SYNERGY_ENTERPRISE: ${{ matrix.enterprise }}
      SYNERGY_NO_TESTS: "1"
      SYNERGY_STATIC_OPENSSL: "1"
      CODESIGN_ID: "Developer ID Application: Symless Ltd (4HX897Y6GJ)"
    runs-on: macos-12
    strategy:
      matrix:
        enterprise: ['1', '']

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - name: Setup Environment
        run: |
          python3 -m pip install dmgbuild

      - name: Install brew dependencies
        run: |
          brew list openssl &>/dev/null || brew install openssl
          brew list qt5 &>/dev/null || brew install qt5

      - name: Compile
        env:
          #CMAKE_OSX_DEPLOYMENT_TARGET: ${{ matrix.target }}
          CMAKE_OSX_ARCHITECTURES: x86_64
        run: |
          set -x
          mkdir -v build
          cd build
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH="$(brew --prefix openssl);$(brew --prefix qt5)/lib/cmake" ..
          pwd
          ls -a
          . ./version
          make -j
          ls -a
          ls -a bin
      
      - name: Version Info
        id: version
        run: |
          . ./build/version
          SYNERGY_VERSION="${SYNERGY_VERSION_MAJOR}.${SYNERGY_VERSION_MINOR}.${SYNERGY_VERSION_PATCH}"
          SYNERGY_REVISION=$(git rev-parse --short=8 HEAD)
          SYNERGY_DMG_VERSION="${SYNERGY_VERSION}-${SYNERGY_VERSION_STAGE}.${SYNERGY_REVISION}"
          echo "::set-output name=SYNERGY_VERSION_MAJOR::$SYNERGY_VERSION_MAJOR"
          echo "::set-output name=SYNERGY_VERSION_MINOR::$SYNERGY_VERSION_MINOR"
          echo "::set-output name=SYNERGY_VERSION_PATCH::$SYNERGY_VERSION_PATCH"
          echo "::set-output name=SYNERGY_VERSION_STAGE::$SYNERGY_VERSION_STAGE"
          echo "::set-output name=SYNERGY_VERSION_BUILD::$SYNERGY_VERSION_BUILD"
          echo "::set-output name=SYNERGY_VERSION::$SYNERGY_VERSION"
          echo "::set-output name=SYNERGY_REVISION::$SYNERGY_REVISION"
          echo "::set-output name=SYNERGY_DMG_VERSION::$SYNERGY_DMG_VERSION"
          if [ "$SYNERGY_ENTERPRISE" == '1' ]
          then
            SYNERGY_PACKAGE_NAME='synergy-enterprise'
            SYNERGY_REMOTE_FOLDER="synergy-core/v1-core-enterprise/${SYNERGY_VERSION}/${SYNERGY_VERSION_STAGE}/b${SYNERGY_VERSION_BUILD}-${SYNERGY_REVISION}"
          else
            SYNERGY_PACKAGE_NAME='synergy'
            SYNERGY_REMOTE_FOLDER="synergy-core/v1-core-standard/${SYNERGY_VERSION}/${SYNERGY_VERSION_STAGE}/b${SYNERGY_VERSION_BUILD}-${SYNERGY_REVISION}"
          fi
          SYNERGY_DMG_FILENAME="${SYNERGY_PACKAGE_NAME}_${SYNERGY_DMG_VERSION}_macos-10.13_x86-64.dmg"
          echo "SYNERGY_REMOTE_FOLDER: $SYNERGY_REMOTE_FOLDER"
          echo "::set-output name=SYNERGY_REMOTE_FOLDER::$SYNERGY_REMOTE_FOLDER"
          echo "::set-output name=SYNERGY_PACKAGE_NAME::$SYNERGY_PACKAGE_NAME"
          echo "::set-output name=SYNERGY_DMG_FILENAME::$SYNERGY_DMG_FILENAME"

      - name: Sign applicaiton
        run: |
          set -x
          export PATH="$(brew --prefix qt5)/bin:$PATH"
          pwd
          macdeployqt ${{ github.workspace }}/build/bundle/Synergy.app -codesign="$CODESIGN_ID"
          codesign -f --options runtime --deep -s "$CODESIGN_ID" ${{ github.workspace }}/build/bundle/Synergy.app
          ln -s /Applications ${{ github.workspace }}/build/bundle/Applications

      - name: Create Installer
        env:
          SYNERGY_DMG_FILENAME: ${{ steps.version.outputs.SYNERGY_DMG_FILENAME }}
        run: |
          dmgbuild \
            -s CI/MacOS/installator_settings.py \
            -D app=${{ github.workspace }}/build/bundle/Synergy.app \
            -D background=${{ github.workspace }}/build/bundle/Synergy.app/Contents/Resources/.installer_background.tiff \
            "Synergy" \
            $SYNERGY_DMG_FILENAME
          mkdir pkg
          mv $SYNERGY_DMG_FILENAME pkg/
          cd pkg
          md5 -r $SYNERGY_DMG_FILENAME >> $SYNERGY_DMG_FILENAME.checksum.txt
          shasum $SYNERGY_DMG_FILENAME >> $SYNERGY_DMG_FILENAME.checksum.txt
          shasum -a 256 $SYNERGY_DMG_FILENAME >> $SYNERGY_DMG_FILENAME.checksum.txt

      - uses: actions/upload-artifact@v2
        #if: "github.event_name == 'pull_request'"
        with:
          name: macos-12-build-test
          path: ${{ github.workspace }}/pkg/*
          retention-days: 1
